- name: Install ZSH
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install Oh My Zsh
  become: false
  ansible.builtin.shell: >
    env KEEP_ZSHRC=yes RUNZSH=no CHSH=no UNATTENDED=1
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Check if Starship is already installed
  ansible.builtin.command: "which starship"
  register: starship_check
  changed_when: false
  failed_when: false
  check_mode: false

- name: Download Starship install script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'
  when: starship_check.rc != 0

- name: "Install Starship"
  ansible.builtin.command: "/tmp/starship_install.sh -y"
  become: true
  when: starship_check.rc != 0

- name: Remove Starship install script
  ansible.builtin.file:
    path: /tmp/starship_install.sh
    state: absent
  when: starship_check.rc != 0

- name: Install Zoxide
  become: false
  ansible.builtin.shell: curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/zoxide"
