---
- name: Install ZSH
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install Oh My Zsh
  become: false
  ansible.builtin.shell: >
    env KEEP_ZSHRC=yes RUNZSH=no CHSH=no UNATTENDED=1
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.oh-my-zsh"

- name: Check if Starship is installed
  ansible.builtin.stat:
    path: /usr/local/bin/starship
  register: starship_bin

- name: Install Starship
  block:
    - name: Download Starship install script
      ansible.builtin.get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship_install.sh
        mode: '0755'

    - name: Run Starship installer
      ansible.builtin.shell: /tmp/starship_install.sh --yes
      become: true

    - name: Remove Starship install script
      ansible.builtin.file:
        path: /tmp/starship_install.sh
        state: absent
  when: not starship_bin.stat.exists

- name: Download Zoxide installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
    dest: /tmp/install_zoxide.sh
    mode: "0755"

- name: Run Zoxide installer
  ansible.builtin.command: /tmp/install_zoxide.sh
  args:
    creates: "{{ ansible_user_dir }}/.local/bin/zoxide"

- name: Remove Zoxide installer script
  ansible.builtin.file:
    path: /tmp/install_zoxide.sh
    state: absent
