---
home: "{{ ansible_env.HOME }}/.config"
ansible_python_interpreter: auto_silent

user:
  name: "Jakub Karp"
  email: "quni.inne@gmail.com"
  username: "fn-jakubkarp"

default_roles:
  - networking
  - languages
  - terminal

custom_apt_repositories:
  - name: eza
    key_url: "https://raw.githubusercontent.com/eza-community/eza/main/deb.asc"
    key_dest: "/etc/apt/keyrings/gierens.asc"
    repo_line: "deb [signed-by=/etc/apt/keyrings/gierens.asc] http://deb.gierens.de stable main"
    filename: "gierens"

go:
  packages:
    - package: github.com/go-task/task/v3/cmd/task@latest
      cmd: task
    - package: github.com/joshmedeski/sesh/v2@latest
      cmd: sesh
    - package: golang.org/x/tools/gopls@latest
      cmd: gopls
